### ISSUE TITLE
Can't chdir to '/var/vcap/store/redis': No such file or directory

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bpm-release#17]
My bpm-managed redis-server cannot access its persistent storage area.

```
==> /var/vcap/sys/log/redis/redis.log <==
1:C 13 Oct 09:48:11.763 # Can't chdir to '/var/vcap/store/redis': No such file or directory
```

The bpm.yml is:

```yaml
---
processes:
- name: redis
  executable: /var/vcap/packages/redis/bin/redis-server
  args:
  - /var/vcap/jobs/redis/config/redis.conf
  volumes:
  - /var/vcap/store/redis
```

The pre-start for the job is:

```bash
#!/bin/bash

mkdir -p /var/vcap/store/redis
chown vcap:vcap -R /var/vcap/store/redis
```

Is there something else I need to do to allow a process inside bpm to access its volumes?

Repo is at https://github.com/cloudfoundry-community/redis-boshrelease/tree/bpm
