### ISSUE TITLE
Concern: single bosh release of `bpm` per deployment

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bpm-release#24]
In https://github.com/cloudfoundry-community/kafka-service-broker-boshrelease/blob/master/manifests/kafka-service-broker.yml I have three different jobs from two different BOSH releases using `bpm`. Additionally, in future the https://github.com/cppforlife/zookeeper-release/tree/bpm/jobs/zookeeper job will support `bpm` hopefully.

Between bpm 0.1.0 and 0.2.0 there was a breaking change to the `bpm.yml` file. As such, each job using `bpm` needed to be upgraded - it must either run against bpm 0.1.0 or 0.2.0.

But BOSH does not support a deployment manifest containing multiple versions of the same release name.

This might cause BOSH release developers to not move forward to newer `bpm` versions because they can't run it in the deployments which contain other jobs using the older `bpm` version. People will be stuck. bpm 0.2.0 might be the last bpm version some people ever use!

Proposals:

* `bpm` commits to never making breaking changes to `bpm.yml` ever again
* `bpm` adds a `schema: 0.2.0` to `bpm.yml` and it supports historical versions of the `bpm.yml` file format
* BOSH adds support for multiple releases with the same name in a deployment manifest. E.g. /cc @cppforlife @dpb587-pivotal 

    ```yaml
    releases:
    - name: bpm
      version: 0.2.0
      alias: bpm-0-2-0
    - name: bpm
      version: 0.3.0
      alias: bpm-0-3-0
    
    instance_groups:
    - name: using-old-bpm
      jobs:
      - name: old-bpm
        release: bpm-0-2-0
    - name: using-new-bpm
      jobs:
      - name: new-bpm
        release: bpm-0-3-0
```
